apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi  # Ensure this matches the PVC request
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-data  # Path on the node where data will be stored
